
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cccr-orchestrator
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.healthcare.cccr.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cccr_db
    username: admin
    password: password

app:
  topics:
    claim-submitted: claim-submitted-topic
    claim-validated: claim-validated-topic
    claim-reviewed: claim-reviewed-topic
    claim-processed: claim-processed-topic
    dead-letter: cccr-dead-letter-topic