
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
        - name: event-processor
          image: <registry>/event-processor:latest
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          ports:
            - containerPort: 8080
          env:
            - name: EVENTHUB_CONN
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: eventhub-conn
            - name: COSMOS_URI
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: cosmos-uri
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
