
name: Pact Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  consumer-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Consumer Pact Tests
        run: mvn test -Dtest=UserServiceConsumerPactTest
      - name: Publish Pacts
        run: |
          mvn pact:publish
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

  provider-tests:
    runs-on: ubuntu-latest
    needs: consumer-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Verify Provider against Pacts
        run: |
          mvn test -Dtest=UserServiceProviderPactTest
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
--- Benefits of PACT Contract Testing:
---     Early Detection: Catch breaking changes before deployment
---     Independent Deployment: Deploy services independently with confidence
---     Documentation: Contracts serve as API documentation
---     Team Autonomy: Consumer and provider teams can work independently
---     CI/CD Integration: Automated verification in pipelines          